### ISSUE TITLE
Disable budgie/gnome powersave kek

### ISSUE THREAD

**Issue by mchalunderscore** [crystal-linux/iso#1]
Issue first opened by @SomethingGeneric

**Comment by SomethingGeneric** [comment]
and auto-lock. i think this is still an issue

**Comment by mchalunderscore** [comment]
Currently this is at least solved by setting the user's description to "Password: crystal" or something along those lines so the user sees what to write in if they are logged out. There's gotta be a way around this though, would maybe having no password on the user mitigate this? Autologin might still work that way

**Comment by mchalunderscore** [comment]
> Currently this is at least solved by setting the user's description to "Password: crystal" or something along those lines so the user sees what to write in if they are logged out. There's gotta be a way around this though, would maybe having no password on the user mitigate this? Autologin might still work that way

I'm not home so I can't test but if someone could try this it'd be much appreciated

**Comment by SomethingGeneric** [comment]
No-password makes a lot of things upset, but I suppose we could work around it with passwordless sudo, too? And yeah, I can test it but I want to do a few other bits first.

For the meantime, how do we set description again? :disappointed_relieved:

**Comment by mchalunderscore** [comment]
It's already done in `iso-chrooted.sh` iirc

**Comment by SomethingGeneric** [comment]
if it's in `chrooted-iso.sh` i can't spot it

**Comment by mchalunderscore** [comment]
> if it's in `chrooted-iso.sh` i can't spot it

https://github.com/crystal-linux/iso/blob/main/chrooted-iso.sh#L9

**Comment by SomethingGeneric** [comment]
Oh sweet lol mb

**Comment by mchalunderscore** [comment]
Could this be considered closed for now? @SomethingGeneric

**Comment by SomethingGeneric** [comment]
I mean yeah we can leave this closed I think until we properly implement the new Onyx and then we can hopefully address it properly.
