### ISSUE TITLE
[FEATURE]: Manual partitioning

### ISSUE THREAD

**Issue by hubergrzegorz** [crystal-linux/iso#13]
### Is your feature request related to a problem? Please describe.

There is no option to manually set the partition during the installation

### Describe the solution you'd like

New release :)

### Describe alternatives you've considered

New release :)

**Comment by SomethingGeneric** [comment]
Hi! Thanks for trying out the ISO. Work on manual partitioning in the installer is in progress over on the jade_gui repo. I’d link it, but I’m on mobile. Sorry!
