### ISSUE TITLE
[FEATURE]: Snap package support built in alongside the already included flatpak

### ISSUE THREAD

**Issue by heidiwenger** [crystal-linux/iso#15]
### Is your feature request related to a problem? Please describe.

Distros which claim to be user friendly and embracing new unifying technologies still don't have the new comer friendly implementations to simply have all sources to get apps. A normal user don't care about packaging formats and such.  

### Describe the solution you'd like

A built in support for "all three" distro agnostic packages: snaps, flatpaks and appimages. This is how Manjaro Linux for example does it. Why not go all in if one takes this route? All packages are not available as snaps and others not as flatpak, and AUR packages (and the likes) are unsafe and usually not sandboxed.

### Describe alternatives you've considered

BAUH could be of use or example? https://github.com/vinifmor/bauh

### Additional context

Every single part of Snap that you come into contact with is open source. The package format, the daemon, the website (snapcraft.io), and the Snap Store that runs on your system. You can also SELF HOST snaps, despite what the small but effectively negative bunch in Reddit and other places claim about snaps.

The only part that is not is some piece of the backend on Ubuntu's servers.

People that have a problem with snaps act like they are blind to the option of disabling that, and those are advanced users.

**Comment by axtloss** [comment]
We don't plan on supporting snaps in any way, flatpaks are easier to support (since they don't require some snapd service) and are in the actual arch repos, meaning we won't have to package snap ourselves.
Flatpaks are enough for the average user, snaps would add an extra thing to maintain which we'd like to avoid.

However users who want to use snap can still install it themselves and use it.

**Comment by heidiwenger** [comment]
> We don't plan on supporting snaps in any way, flatpaks are easier to support (since they don't require some snapd service) and are in the actual arch repos, meaning we won't have to package snap ourselves. Flatpaks are enough for the average user, snaps would add an extra thing to maintain which we'd like to avoid.
> 
> However users who want to use snap can still install it themselves and use it.

Why would you need to package anything? Snacraft.io is there with thousands of apps. There are about 1500 flatpak around only. Many apps are only easily installed right now as a snap. Ruling snaps out makes Crystal Linux less beginner friendly. Just saying.

**Comment by axtloss** [comment]
We would have to package snap itself, snapd is not in the arch repos but in the aur, we would have to build it from the aur and ship it in our repos which takes build time and extra effort.

**Comment by mrshmllow** [comment]
exceedingly rare snap user sighting

**Comment by hericiumvevo** [comment]
> We would have to package snap itself, snapd is not in the arch repos but in the aur, we would have to build it from the aur and ship it in our repos which takes build time and extra effort.

Launching apps packaged as snaps will take even more time

**Comment by heidiwenger** [comment]
> We would have to package snap itself, snapd is not in the arch repos but in the aur, we would have to build it from the aur and ship it in our repos which takes build time and extra effort.

It's not like it's a quick-here-now thing. You have just started, i know. You'd only have to do this building once, right? I mean, Manjaro Linux supports all of these assets OOTB. The new comers (and "beginner friendly distros") need these all, i think. 

Nothing matters more than software availability (safely, sandbox) and EASILY. But yeah, you do you of course.

**Comment by heidiwenger** [comment]
> > We would have to package snap itself, snapd is not in the arch repos but in the aur, we would have to build it from the aur and ship it in our repos which takes build time and extra effort.
> 
> Launching apps packaged as snaps will take even more time

What do you mean? Snaps are ready in Snapcraf.io and flatpaks similarly in trusted flathub. Any other sources would be the same as the cumbersome (and non user friendly, dangerous) PPA-hassle. AUR is not a reliable and to be recommended source for new comers.

**Comment by mchalunderscore** [comment]
Crystal is not aiming to be a hold-your-hand beginner-friendly distribution, we're a distribution that works with application developers to enable Linux users and potential Developers to make the most out of their system; Most developers we've talked to, and we work, with simply prefer packaging for Flatpak. Our focus on accessibility doesn't equate to being beginner-friendly per se

**Comment by heidiwenger** [comment]
> Crystal is not aiming to be a hold-your-hand beginner-friendly distribution, we're a distribution that works with application developers to enable Linux users and potential Developers to make the most out of their system; Most developers we've talked to, and we work with simply prefer packaging for Flatpak. Our focus on accessibility doesn't equate to being beginner-friendly per se

It is subjective what is "hold your hand friendly" of course. But including all three, snaps, flatpak and appimage, would definitely help app installation and availability. In my view AUR (and the likes) are dangerous.

**Comment by mchalunderscore** [comment]
> > Crystal is not aiming to be a hold-your-hand beginner-friendly distribution, we're a distribution that works with application developers to enable Linux users and potential Developers to make the most out of their system; Most developers we've talked to, and we work with simply prefer packaging for Flatpak. Our focus on accessibility doesn't equate to being beginner-friendly per se
> 
> It is subjective what is "hold your hand friendly" of course. But including all three, snaps, flatpak and appimage, would definitely help app installation and availability. In my view AUR (and the likes) are dangerous.

And we plan to make sure the user knows that the AUR is not a reliable source for your packages. Again, let me reiterate:

- `snap` is packaged in the AUR not the official repositories, we'd have to put extra work into maintaining the `snap` package that could be put into other improvements
- Application availability is already targeted by Flatpak, which we prefer because, again, we work with application developers that prefer Flatpak. We will not compromise on the wants and/or needs of our developers, as without them, we would not have any applications
- Snaps have notorious issues
  - To quote [u/quaderrordemonstand](https://www.reddit.com/r/linux/comments/j3ajnf/comment/g7eckk2/?utm_source=share&utm_medium=web2x&context=3) on Reddit:
> Snaps are slow to install, slow to start, take too much RAM, too much disk space and they auto-update themselves without asking, taking up bandwidth. They don't respect your system setting and snap versions of apps are often restricted compared to their non-snap counterpart.

Many of the aforementioned issues are directly addressed and don't exist on Flatpak's `ostree`-based system.

I understand software availability is a concern, however targeting `snap` seems like it wouldn't be nearly as beneficial to us and our community as targeting Flatpak and other related technologies, as well as taking time out of our lives, since we are all busy individuals who simply choose to contribute

**Comment by heidiwenger** [comment]
> > > 
> > Snaps are slow to install, slow to start, take too much RAM, too much disk space and they auto-update themselves without asking, taking up bandwidth. They don't respect your system setting and snap versions of apps are often restricted compared to their non-snap counterpart.

The slower start time is about to get fixed. Flatpaks start slower than regular packages also. Snaps don't take more RAM than flatpak either; Alan Pope has demonstrated this false belief. It's just not true. The diskspace: one needs the dependencies anyways, do they not? 

There is much disinformation and "blind hate" towards snaps still, but things are getting more accepted because the true information increases about what snaps even are and are capable of. They are NOT similar to flatpak (that is another misconception).

I mean, i understand your claims. These are just not drop in replacements to each other. One can snap even a Linux kernel, server side software and so much more. Flatpak is only for desktop use strictly.

**Comment by heidiwenger** [comment]
Snaps don't have any effect on app performance. At most, it might be argued that the snap daemon has some effect on ram consumption. But all in all, we are talking software availability and secure easiness here, in my view.

**Comment by axtloss** [comment]
> Flatpaks start slower than regular packages also

no they don't, flatpak in some cases even outperform regular packages.

> The diskspace: one needs the dependencies anyways, do they not?

Yes, dependencies are needed, but snap handles that poorly, with snap you have everything in a squashfs image, no deduplication whatsoever. With flatpak dependencies are deduplicated, meaning that if a file has the exact same hash (meaning it's the same file) the file will only be in the filesystem once, the more flatpak packages you have the more space efficient they are.

> Snaps don't have any effect on app performance

They do, due to them using squashfs images to distribute the apps the time to open application takes longer due to snap having to extract this image.

Having the arch repos + flatpak/flathub + aur + nix already offers enough packages, snap and appimage both add extra effort that is not needed.

**Comment by mchalunderscore** [comment]
> I mean, i understand your claims. These are just not drop in replacements to each other. One can snap even a Linux kernel, server side software and so much more. Flatpak is only for desktop use strictly.

I understand your position on this too, however in our use case, going out of our way to support snaps has more cons than pros, so we will not be going forward with this

**Comment by heidiwenger** [comment]
> > Flatpaks start slower than regular packages also
> 
> no they don't, flatpak in some cases even outperform regular packages.
> 
> > The diskspace: one needs the dependencies anyways, do they not?
> 
> Yes, dependencies are needed, but snap handles that poorly, with snap you have everything in a squashfs image, no deduplication whatsoever. With flatpak dependencies are deduplicated, meaning that if a file has the exact same hash (meaning it's the same file) the file will only be in the filesystem once, the more flatpak packages you have the more space efficient they are.

But flatpak don't always have all the required dependencies. Nor does appimage. snaps ALWAYS do. And always sandboxed; flatpak are not.

> 
> > Snaps don't have any effect on app performance
> 
> They do, due to them using squashfs images to distribute the apps the time to open application takes longer due to snap having to extract this image.
> 
Startup time is not the same as the performing of app itself AFTER the launch. So no, this is not true. Firefox startup time has been for example split in half.

**Comment by heidiwenger** [comment]
> > I mean, i understand your claims. These are just not drop in replacements to each other. One can snap even a Linux kernel, server side software and so much more. Flatpak is only for desktop use strictly.
> 
> I understand your position on this too, however in our use case, going out of our way to support snaps has more cons than pros, so we will not be going forward with this

Yep! Good luck in your endeavours!

**Comment by hericiumvevo** [comment]
> But flatpak don't always have all the required dependencies. Nor does appimage. snaps ALWAYS do. And always sandboxed; flatpak are not.
This is simply not true 
Please stop spreading misinformation

**Comment by heidiwenger** [comment]
> > But flatpak don't always have all the required dependencies. Nor does appimage. snaps ALWAYS do. And always sandboxed; flatpak are not.
> > This is simply not true
> > Please stop spreading misinformation

What? I have faced this many a occasion: flatpak don't always have all the needed dependencies.

**Comment by TheEvilSkeleton** [comment]
> But flatpak don't always have all the required dependencies. Nor does appimage. snaps ALWAYS do.

Source?

> And always sandboxed; flatpak are not.

Source?

**Comment by axtloss** [comment]
> And always sandboxed; flatpak are not.

from https://ubuntu.com/blog/how-to-snap-introducing-classic-confinement :
> With snapd 2.20, a new confinement policy is introduced: “classic”, designed to cater for all your scripting and tooling needs. Snaps declaring their confinement as “classic”, have access to the rest of the system, as most legacy (debian packages for example) packaged apps do, while still benefiting from the ci-integrated store model, with automated updates, rollbacks to older versions, release channels, etc.

I can't find anything about being able to completely disable the sandbox in flatpak, did you confuse flatpak with snap?

**Comment by mchalunderscore** [comment]
~~Please, all, let's keep this conversation productive, snide comments are not necessary here~~

Locking this to prevent further arguments
