### ISSUE TITLE
[FEATURE]: Request ISO-8601 date format be standardized on

### ISSUE THREAD

**Issue by em-winterschon** [crystal-linux/iso#21]
### Is your feature request related to a problem? Please describe.

There are multiple date formats in use for the releases, tags, branches, comments, etc... standardizing on ISO-8601 will assist with ensuring Crystal Linux is following general industry trends and expectations on date format usage.

### Describe the solution you'd like

Stop using non-ISO-8601 date formats and standardize on ISO-8601 format: https://en.wikipedia.org/wiki/ISO_8601

### Describe alternatives you've considered

No alternatives are appropriate.

**Comment by SomethingGeneric** [comment]
This is a fantastic point. Thanks! @axtloss while we're at it, having hour/min/sec is a bit redundant given that we're certainly no-longer releasing ISOs more often than once a day
