### ISSUE TITLE
[BUG]: Crystal-mirrorlist could not be read

### ISSUE THREAD

**Issue by Neocamelus** [crystal-linux/iso#35]
### Describe the bug

Hello, 

I have the following error message:
config file /etc/pacman.d/crystal-mirrorlist could not be read: No such file or directory

### To reproduce the bug

On ArcoLinux, after installing dependencies
I run the command `./build.sh --build-iso`

### Expected behavior

I want to build an ISO.

**Comment by SomethingGeneric** [comment]
Hi! We've moved this project to https://git.getcryst.al/crystal/misc/iso

Could you please re-open the issue there?
